language:
  - cpp

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

# Install packages differs for container-based infrastructure
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F
# * http://stackoverflow.com/a/30925448/2288008
addons:
  apt:
    packages:
      - python3

      # python3-pip package is not available, use 'easy_install3':
      # * https://github.com/travis-ci/apt-package-whitelist/issues/768
      - python3-setuptools # easy_install3

matrix:
  include:
    - os: linux

install:
  # Info about OS
  - uname -a

  # Workaround for https://github.com/travis-ci/travis-ci/issues/8363
  - pyenv global system 3.5

  - which pip3
  - pip3 --version

  - which python3
  - python3 --version

  - pip3 install --user requests

script:
  - python3 -c 'import requests'
