# OSX/Linux (https://github.com/travis-ci-tester/toolchain-table)

language: cpp

os:
  - linux
  - osx

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

# Install packages differs for container-based infrastructure
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F
# * http://stackoverflow.com/a/30925448/2288008
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - python3
      - python3-requests

      # https://github.com/travis-ci-tester/travis-test-clang-cxx-11
      - libstdc++-4.8-dev

      # https://github.com/travis-ci-tester/travis-test-gcc-cxx-11
      - g++-4.8

install:
  # Install Python 3
  - if [[ "`uname`" == "Darwin" ]]; then brew install python3; fi
  - which python3
  - python3 --version

  # Install 'requests'
  - if [[ "`uname`" == "Darwin" ]]; then pip3 install requests; fi

script:
  - python3 -c 'import requests'
